import { ref, computed } from 'vue'
import { defineStore } from 'pinia'
import { useUIStore } from './ui'

export const useProductStore = defineStore('products', () => {
  const products = ref([
    // Laptops (20)
    {
      id: 1,
      name: 'NovaBook Pro 16"',
      category: 'Laptops',
      brand: 'Nova',
      price: 2899.99,
      salePrice: 2699.99,
      featured: true,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=NovaBook+Pro',
      specs: { ram: '16GB', cpu: 'Intel Core i9', storage: '1TB SSD', screenSize: '16"' },
    },
    {
      id: 8,
      name: 'NovaBook Air 14"',
      category: 'Laptops',
      brand: 'Nova',
      price: 1799.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=NovaBook+Air',
      specs: { ram: '16GB', cpu: 'Intel Core i7', storage: '512GB SSD', screenSize: '14"' },
    },
    {
      id: 16,
      name: 'QuantumGamer X17',
      category: 'Laptops',
      brand: 'Quantum',
      price: 3499.0,
      salePrice: 3299.0,
      featured: true,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=QuantumGamer',
      specs: { ram: '32GB', cpu: 'AMD Ryzen 9', storage: '2TB SSD', screenSize: '17"' },
    },
    {
      id: 17,
      name: 'ChronoWorkstation 15',
      category: 'Laptops',
      brand: 'Chrono',
      price: 4200.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=ChronoWorkstation',
      specs: { ram: '64GB', cpu: 'Intel Core i9', storage: '4TB SSD', screenSize: '15.6"' },
    },
    {
      id: 18,
      name: 'NovaBook Lite 13"',
      category: 'Laptops',
      brand: 'Nova',
      price: 1299.0,
      salePrice: 1149.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=NovaBook+Lite',
      specs: { ram: '8GB', cpu: 'Intel Core i5', storage: '256GB SSD', screenSize: '13.3"' },
    },
    {
      id: 28,
      name: 'Apex Predator G15',
      category: 'Laptops',
      brand: 'Apex',
      price: 2199.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Predator',
      specs: { ram: '16GB', cpu: 'AMD Ryzen 7', storage: '1TB SSD', screenSize: '15.6"' },
    },
    {
      id: 29,
      name: 'Quantum Creator Z16',
      category: 'Laptops',
      brand: 'Quantum',
      price: 3899.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Creator',
      specs: { ram: '32GB', cpu: 'Intel Core i9', storage: '2TB SSD', screenSize: '16"' },
    },
    {
      id: 30,
      name: 'Aether UltraSlim 13',
      category: 'Laptops',
      brand: 'Aether',
      price: 1599.0,
      salePrice: 1399.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+UltraSlim',
      specs: { ram: '16GB', cpu: 'Intel Core i7', storage: '1TB SSD', screenSize: '13.4"' },
    },
    {
      id: 31,
      name: 'Chrono Traveler 14',
      category: 'Laptops',
      brand: 'Chrono',
      price: 1450.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Chrono+Traveler',
      specs: { ram: '8GB', cpu: 'AMD Ryzen 5', storage: '512GB SSD', screenSize: '14"' },
    },
    {
      id: 32,
      name: 'NovaBook Pro 14"',
      category: 'Laptops',
      brand: 'Nova',
      price: 2599.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=NovaBook+Pro+14',
      specs: { ram: '16GB', cpu: 'Intel Core i7', storage: '1TB SSD', screenSize: '14"' },
    },
    {
      id: 85,
      name: 'Quantum Stealth 14"',
      category: 'Laptops',
      brand: 'Quantum',
      price: 2899.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Stealth',
      specs: { ram: '32GB', cpu: 'AMD Ryzen 7', storage: '1TB SSD', screenSize: '14"' },
    },
    {
      id: 86,
      name: 'Apex Titan X16',
      category: 'Laptops',
      brand: 'Apex',
      price: 4800.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Titan',
      specs: { ram: '64GB', cpu: 'Intel Core i9', storage: '2TB SSD', screenSize: '16"' },
    },
    {
      id: 87,
      name: 'Aether Flow 15"',
      category: 'Laptops',
      brand: 'Aether',
      price: 1999.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Flow',
      specs: { ram: '16GB', cpu: 'Intel Core i7', storage: '1TB SSD', screenSize: '15.6"' },
    },
    {
      id: 88,
      name: 'ChronoBook Flip',
      category: 'Laptops',
      brand: 'Chrono',
      price: 1650.0,
      salePrice: 1450.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=ChronoBook+Flip',
      specs: { ram: '16GB', cpu: 'AMD Ryzen 7', storage: '512GB SSD', screenSize: '13.3"' },
    },
    {
      id: 89,
      name: 'Nova Enterprise E5',
      category: 'Laptops',
      brand: 'Nova',
      price: 1899.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Nova+Enterprise',
      specs: { ram: '16GB', cpu: 'Intel Core i5', storage: '1TB SSD', screenSize: '15.6"' },
    },
    {
      id: 90,
      name: 'QuantumGamer Lite',
      category: 'Laptops',
      brand: 'Quantum',
      price: 1999.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=QuantumGamer+Lite',
      specs: { ram: '16GB', cpu: 'Intel Core i7', storage: '1TB SSD', screenSize: '15.6"' },
    },
    {
      id: 91,
      name: 'Apex Nomad 13',
      category: 'Laptops',
      brand: 'Apex',
      price: 1350.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Nomad',
      specs: { ram: '8GB', cpu: 'Intel Core i5', storage: '512GB SSD', screenSize: '13.3"' },
    },
    {
      id: 92,
      name: 'Aether Vision 17"',
      category: 'Laptops',
      brand: 'Aether',
      price: 3200.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Vision',
      specs: { ram: '32GB', cpu: 'Intel Core i9', storage: '1TB SSD', screenSize: '17"' },
    },
    {
      id: 93,
      name: 'Chrono Coder 15"',
      category: 'Laptops',
      brand: 'Chrono',
      price: 2200.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Chrono+Coder',
      specs: { ram: '32GB', cpu: 'AMD Ryzen 7', storage: '1TB SSD', screenSize: '15.6"' },
    },
    {
      id: 94,
      name: 'NovaBook Essential',
      category: 'Laptops',
      brand: 'Nova',
      price: 999.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=NovaBook+Essential',
      specs: { ram: '8GB', cpu: 'Intel Core i3', storage: '256GB SSD', screenSize: '15.6"' },
    },
    {
      id: 2,
      name: 'AetherPhone XV',
      category: 'Smartphones',
      brand: 'Aether',
      price: 1599.0,
      salePrice: 1499.0,
      featured: true,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=AetherPhone+XV',
      specs: { storage: '256GB' },
    },
    {
      id: 9,
      name: 'AetherPhone SE',
      category: 'Smartphones',
      brand: 'Aether',
      price: 899.0,
      salePrice: 799.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=AetherPhone+SE',
      specs: { storage: '128GB' },
    },
    {
      id: 19,
      name: 'Apex One Pro',
      category: 'Smartphones',
      brand: 'Apex',
      price: 1399.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+One+Pro',
      specs: { storage: '512GB' },
    },
    {
      id: 20,
      name: 'AetherPhone XV Max',
      category: 'Smartphones',
      brand: 'Aether',
      price: 1899.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=AetherPhone+Max',
      specs: { storage: '1TB' },
    },
    {
      id: 33,
      name: 'Quantum Leap 5G',
      category: 'Smartphones',
      brand: 'Quantum',
      price: 1199.0,
      salePrice: 1049.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Leap',
      specs: { storage: '256GB' },
    },
    {
      id: 34,
      name: 'Nova Connect',
      category: 'Smartphones',
      brand: 'Nova',
      price: 699.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Nova+Connect',
      specs: { storage: '128GB' },
    },
    {
      id: 35,
      name: 'Chrono Fold 3',
      category: 'Smartphones',
      brand: 'Chrono',
      price: 2199.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Chrono+Fold',
      specs: { storage: '512GB' },
    },
    {
      id: 36,
      name: 'Apex One Mini',
      category: 'Smartphones',
      brand: 'Apex',
      price: 999.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+One+Mini',
      specs: { storage: '256GB' },
    },
    {
      id: 37,
      name: 'AetherPhone Ultra',
      category: 'Smartphones',
      brand: 'Aether',
      price: 2099.0,
      salePrice: 1899.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=AetherPhone+Ultra',
      specs: { storage: '1TB' },
    },
    {
      id: 38,
      name: 'Quantum Shift',
      category: 'Smartphones',
      brand: 'Quantum',
      price: 1750.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Shift',
      specs: { storage: '512GB' },
    },
    {
      id: 95,
      name: 'Nova Link 5G',
      category: 'Smartphones',
      brand: 'Nova',
      price: 850.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Nova+Link',
      specs: { storage: '256GB' },
    },
    {
      id: 96,
      name: 'Apex Challenger',
      category: 'Smartphones',
      brand: 'Apex',
      price: 750.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Challenger',
      specs: { storage: '128GB' },
    },
    {
      id: 97,
      name: 'Quantum Photon',
      category: 'Smartphones',
      brand: 'Quantum',
      price: 1999.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Photon',
      specs: { storage: '1TB' },
    },
    {
      id: 98,
      name: 'AetherPhone Classic',
      category: 'Smartphones',
      brand: 'Aether',
      price: 1099.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Classic',
      specs: { storage: '256GB' },
    },
    {
      id: 99,
      name: 'Chrono Snap',
      category: 'Smartphones',
      brand: 'Chrono',
      price: 1300.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Chrono+Snap',
      specs: { storage: '256GB' },
    },
    {
      id: 100,
      name: 'Nova Core',
      category: 'Smartphones',
      brand: 'Nova',
      price: 499.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Nova+Core',
      specs: { storage: '64GB' },
    },
    {
      id: 101,
      name: 'Apex Edge+',
      category: 'Smartphones',
      brand: 'Apex',
      price: 1599.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Edge%2B',
      specs: { storage: '512GB' },
    },
    {
      id: 102,
      name: 'Quantum Vision',
      category: 'Smartphones',
      brand: 'Quantum',
      price: 1400.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Vision',
      specs: { storage: '256GB' },
    },
    {
      id: 103,
      name: 'AetherPhone Compact',
      category: 'Smartphones',
      brand: 'Aether',
      price: 1250.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Compact',
      specs: { storage: '128GB' },
    },
    {
      id: 104,
      name: 'Chrono Flip 2',
      category: 'Smartphones',
      brand: 'Chrono',
      price: 1550.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Chrono+Flip+2',
      specs: { storage: '256GB' },
    },
    {
      id: 3,
      name: 'QuantumPad Air',
      category: 'Tablets',
      brand: 'Quantum',
      price: 1199.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=QuantumPad+Air',
      specs: { storage: '256GB' },
    },
    {
      id: 21,
      name: 'QuantumPad Pro 12.9"',
      category: 'Tablets',
      brand: 'Quantum',
      price: 1699.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=QuantumPad+Pro',
      specs: { storage: '512GB' },
    },
    {
      id: 22,
      name: 'NovaTab Go 10"',
      category: 'Tablets',
      brand: 'Nova',
      price: 799.0,
      salePrice: 699.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=NovaTab+Go',
      specs: { storage: '128GB' },
    },
    {
      id: 39,
      name: 'Aether Slate Pro',
      category: 'Tablets',
      brand: 'Aether',
      price: 1450.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Slate+Pro',
      specs: { storage: '256GB' },
    },
    {
      id: 40,
      name: 'ChronoNote 11',
      category: 'Tablets',
      brand: 'Chrono',
      price: 950.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=ChronoNote+11',
      specs: { storage: '128GB' },
    },
    {
      id: 41,
      name: 'QuantumPad Mini',
      category: 'Tablets',
      brand: 'Quantum',
      price: 899.0,
      salePrice: 799.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=QuantumPad+Mini',
      specs: { storage: '256GB' },
    },
    {
      id: 42,
      name: 'Apex Canvas 14',
      category: 'Tablets',
      brand: 'Apex',
      price: 1899.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Canvas',
      specs: { storage: '512GB' },
    },
    {
      id: 43,
      name: 'NovaTab Max 12"',
      category: 'Tablets',
      brand: 'Nova',
      price: 1099.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=NovaTab+Max',
      specs: { storage: '256GB' },
    },
    {
      id: 44,
      name: 'Aether Slate Lite',
      category: 'Tablets',
      brand: 'Aether',
      price: 650.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Slate+Lite',
      specs: { storage: '128GB' },
    },
    {
      id: 45,
      name: 'ChronoNote Plus',
      category: 'Tablets',
      brand: 'Chrono',
      price: 1150.0,
      salePrice: 999.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=ChronoNote+Plus',
      specs: { storage: '256GB' },
    },
    {
      id: 105,
      name: 'QuantumPad Pro 11"',
      category: 'Tablets',
      brand: 'Quantum',
      price: 1299.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=QuantumPad+Pro+11',
      specs: { storage: '256GB' },
    },
    {
      id: 106,
      name: 'NovaTab Kids',
      category: 'Tablets',
      brand: 'Nova',
      price: 399.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=NovaTab+Kids',
      specs: { storage: '64GB' },
    },
    {
      id: 107,
      name: 'Aether Slate Max',
      category: 'Tablets',
      brand: 'Aether',
      price: 1999.0,
      salePrice: 1749.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Slate+Max',
      specs: { storage: '1TB' },
    },
    {
      id: 108,
      name: 'ChronoNote Pro',
      category: 'Tablets',
      brand: 'Chrono',
      price: 1550.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=ChronoNote+Pro',
      specs: { storage: '512GB' },
    },
    {
      id: 109,
      name: 'Apex StudioPad',
      category: 'Tablets',
      brand: 'Apex',
      price: 2100.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+StudioPad',
      specs: { storage: '1TB' },
    },
    {
      id: 110,
      name: 'QuantumPad Go',
      category: 'Tablets',
      brand: 'Quantum',
      price: 750.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=QuantumPad+Go',
      specs: { storage: '128GB' },
    },
    {
      id: 111,
      name: 'NovaTab Pro 11',
      category: 'Tablets',
      brand: 'Nova',
      price: 950.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=NovaTab+Pro',
      specs: { storage: '256GB' },
    },
    {
      id: 112,
      name: 'Aether Slate Basic',
      category: 'Tablets',
      brand: 'Aether',
      price: 850.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Slate+Basic',
      specs: { storage: '128GB' },
    },
    {
      id: 113,
      name: 'Chrono DrawPad',
      category: 'Tablets',
      brand: 'Chrono',
      price: 1350.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Chrono+DrawPad',
      specs: { storage: '256GB' },
    },
    {
      id: 114,
      name: 'Apex Reader',
      category: 'Tablets',
      brand: 'Apex',
      price: 450.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Reader',
      specs: { storage: '64GB' },
    },
    {
      id: 14,
      name: 'QuantumForge Creator',
      category: 'Desktops',
      brand: 'Quantum',
      price: 3250.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=QuantumForge+Creator',
      specs: { ram: '32GB', cpu: 'Intel Core i7', storage: '1TB SSD + 2TB HDD' },
    },
    {
      id: 23,
      name: 'Apex Gaming Rig',
      category: 'Desktops',
      brand: 'Apex',
      price: 4500.0,
      salePrice: 4250.0,
      featured: true,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Gaming+Rig',
      specs: { ram: '32GB', cpu: 'AMD Ryzen 9', storage: '2TB SSD' },
    },
    {
      id: 24,
      name: 'Nova Office Essential',
      category: 'Desktops',
      brand: 'Nova',
      price: 1499.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Nova+Office',
      specs: { ram: '16GB', cpu: 'Intel Core i5', storage: '512GB SSD' },
    },
    {
      id: 46,
      name: 'ChronoWorkstation Pro',
      category: 'Desktops',
      brand: 'Chrono',
      price: 5500.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=ChronoWorkstation',
      specs: { ram: '64GB', cpu: 'Intel Core i9', storage: '4TB SSD' },
    },
    {
      id: 47,
      name: 'Quantum Mini PC',
      category: 'Desktops',
      brand: 'Quantum',
      price: 1100.0,
      salePrice: 950.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Mini+PC',
      specs: { ram: '16GB', cpu: 'AMD Ryzen 5', storage: '512GB SSD' },
    },
    {
      id: 48,
      name: 'Apex Streamer Plus',
      category: 'Desktops',
      brand: 'Apex',
      price: 2999.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Streamer',
      specs: { ram: '32GB', cpu: 'Intel Core i7', storage: '1TB SSD' },
    },
    {
      id: 49,
      name: 'Aether All-in-One 27"',
      category: 'Desktops',
      brand: 'Aether',
      price: 2499.0,
      salePrice: 2299.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+AIO',
      specs: { ram: '16GB', cpu: 'Intel Core i7', storage: '1TB SSD' },
    },
    {
      id: 50,
      name: 'Nova Home PC',
      category: 'Desktops',
      brand: 'Nova',
      price: 999.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Nova+Home+PC',
      specs: { ram: '8GB', cpu: 'Intel Core i3', storage: '256GB SSD' },
    },
    {
      id: 51,
      name: 'QuantumForge Elite',
      category: 'Desktops',
      brand: 'Quantum',
      price: 6200.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=QuantumForge+Elite',
      specs: { ram: '64GB', cpu: 'AMD Ryzen 9', storage: '4TB SSD' },
    },
    {
      id: 52,
      name: 'Apex Compact Gamer',
      category: 'Desktops',
      brand: 'Apex',
      price: 1999.0,
      salePrice: 1799.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Compact+Gamer',
      specs: { ram: '16GB', cpu: 'AMD Ryzen 7', storage: '1TB SSD' },
    },
    {
      id: 115,
      name: 'Chrono Studio Tower',
      category: 'Desktops',
      brand: 'Chrono',
      price: 3800.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Chrono+Studio',
      specs: { ram: '32GB', cpu: 'Intel Core i9', storage: '2TB SSD' },
    },
    {
      id: 116,
      name: 'Nova Micro',
      category: 'Desktops',
      brand: 'Nova',
      price: 850.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Nova+Micro',
      specs: { ram: '8GB', cpu: 'Intel Core i5', storage: '512GB SSD' },
    },
    {
      id: 117,
      name: 'Aether Design Pro',
      category: 'Desktops',
      brand: 'Aether',
      price: 4100.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Design+Pro',
      specs: { ram: '64GB', cpu: 'Intel Core i9', storage: '2TB SSD' },
    },
    {
      id: 118,
      name: 'Apex Pro Rig',
      category: 'Desktops',
      brand: 'Apex',
      price: 6800.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Pro+Rig',
      specs: { ram: '128GB', cpu: 'AMD Threadripper', storage: '4TB SSD' },
    },
    {
      id: 119,
      name: 'Quantum Edge',
      category: 'Desktops',
      brand: 'Quantum',
      price: 2800.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Edge',
      specs: { ram: '32GB', cpu: 'AMD Ryzen 7', storage: '1TB SSD' },
    },
    {
      id: 120,
      name: 'ChronoVR Ready',
      category: 'Desktops',
      brand: 'Chrono',
      price: 3100.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=ChronoVR+Ready',
      specs: { ram: '32GB', cpu: 'Intel Core i7', storage: '1TB SSD' },
    },
    {
      id: 121,
      name: 'Nova Business Tower',
      category: 'Desktops',
      brand: 'Nova',
      price: 1750.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Nova+Business',
      specs: { ram: '16GB', cpu: 'Intel Core i7', storage: '1TB SSD' },
    },
    {
      id: 122,
      name: 'Aether Mini Studio',
      category: 'Desktops',
      brand: 'Aether',
      price: 1600.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Mini+Studio',
      specs: { ram: '16GB', cpu: 'Intel Core i7', storage: '512GB SSD' },
    },
    {
      id: 123,
      name: 'Apex LAN Party Rig',
      category: 'Desktops',
      brand: 'Apex',
      price: 2300.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+LAN+Party',
      specs: { ram: '16GB', cpu: 'AMD Ryzen 5', storage: '1TB SSD' },
    },
    {
      id: 124,
      name: 'Quantum Server Core',
      category: 'Desktops',
      brand: 'Quantum',
      price: 3500.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Server',
      specs: { ram: '64GB', cpu: 'Intel Xeon', storage: '2TB SSD RAID' },
    },
    {
      id: 12,
      name: 'Odyssey Neo G9',
      category: 'Monitors',
      brand: 'Samsung',
      price: 2499.99,
      salePrice: 2299.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Odyssey+Neo+G9',
      specs: { screenSize: '49"', resolution: 'Dual QHD' },
    },
    {
      id: 25,
      name: 'ChronoView 4K Pro',
      category: 'Monitors',
      brand: 'Chrono',
      price: 950.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=ChronoView+4K',
      specs: { screenSize: '27"', resolution: '4K' },
    },
    {
      id: 26,
      name: 'Apex Gaming 240Hz',
      category: 'Monitors',
      brand: 'Apex',
      price: 650.0,
      salePrice: 579.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Gaming+240Hz',
      specs: { screenSize: '27"', resolution: '1440p' },
    },
    {
      id: 27,
      name: 'Nova WorkWide Ultrawide',
      category: 'Monitors',
      brand: 'Nova',
      price: 1100.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Nova+WorkWide',
      specs: { screenSize: '34"', resolution: '1440p' },
    },
    {
      id: 53,
      name: 'Quantum Crystal 5K',
      category: 'Monitors',
      brand: 'Quantum',
      price: 1800.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Crystal+5K',
      specs: { screenSize: '32"', resolution: '5K' },
    },
    {
      id: 54,
      name: 'Aether Display P3',
      category: 'Monitors',
      brand: 'Aether',
      price: 1599.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Display+P3',
      specs: { screenSize: '27"', resolution: '4K' },
    },
    {
      id: 55,
      name: 'ChronoView Portable',
      category: 'Monitors',
      brand: 'Chrono',
      price: 450.0,
      salePrice: 399.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=ChronoView+Portable',
      specs: { screenSize: '15.6"', resolution: '1080p' },
    },
    {
      id: 56,
      name: 'Apex ProArt 32"',
      category: 'Monitors',
      brand: 'Apex',
      price: 1250.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+ProArt',
      specs: { screenSize: '32"', resolution: '4K' },
    },
    {
      id: 57,
      name: 'Nova Basic 24"',
      category: 'Monitors',
      brand: 'Nova',
      price: 299.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Nova+Basic+24',
      specs: { screenSize: '24"', resolution: '1080p' },
    },
    {
      id: 58,
      name: 'Samsung OfficeMaster',
      category: 'Monitors',
      brand: 'Samsung',
      price: 499.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Samsung+OfficeMaster',
      specs: { screenSize: '27"', resolution: '1440p' },
    },
    {
      id: 201,
      name: 'Quantum Ultrafine',
      category: 'Monitors',
      brand: 'Quantum',
      price: 1300.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Ultrafine',
      specs: { screenSize: '27"', resolution: '5K' },
    },
    {
      id: 202,
      name: 'Aether Pro Display XDR',
      category: 'Monitors',
      brand: 'Aether',
      price: 6500.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Pro+XDR',
      specs: { screenSize: '32"', resolution: '6K' },
    },
    {
      id: 203,
      name: 'Chrono FastFrame 360Hz',
      category: 'Monitors',
      brand: 'Chrono',
      price: 899.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Chrono+FastFrame',
      specs: { screenSize: '25"', resolution: '1080p' },
    },
    {
      id: 204,
      name: 'Apex Vision 4K',
      category: 'Monitors',
      brand: 'Apex',
      price: 720.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Vision+4K',
      specs: { screenSize: '28"', resolution: '4K' },
    },
    {
      id: 205,
      name: 'Nova Dual View',
      category: 'Monitors',
      brand: 'Nova',
      price: 680.0,
      salePrice: 599.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Nova+Dual+View',
      specs: { screenSize: '32"', resolution: '1440p' },
    },
    {
      id: 206,
      name: 'Samsung Smart Monitor M8',
      category: 'Monitors',
      brand: 'Samsung',
      price: 899.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Samsung+Smart+M8',
      specs: { screenSize: '32"', resolution: '4K' },
    },
    {
      id: 207,
      name: 'Quantum Curve 34"',
      category: 'Monitors',
      brand: 'Quantum',
      price: 999.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Curve+34',
      specs: { screenSize: '34"', resolution: '1440p' },
    },
    {
      id: 208,
      name: 'Aether ColorPro 27',
      category: 'Monitors',
      brand: 'Aether',
      price: 850.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+ColorPro',
      specs: { screenSize: '27"', resolution: '1440p' },
    },
    {
      id: 209,
      name: 'Chrono Gamer 24"',
      category: 'Monitors',
      brand: 'Chrono',
      price: 320.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Chrono+Gamer+24',
      specs: { screenSize: '24"', resolution: '1080p' },
    },
    {
      id: 210,
      name: 'Apex Widescreen 38"',
      category: 'Monitors',
      brand: 'Apex',
      price: 1400.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Widescreen',
      specs: { screenSize: '38"', resolution: 'UWQHD+' },
    },
    {
      id: 6,
      name: 'SoundWeave Pro',
      category: 'Audio',
      brand: 'SoundWeave',
      price: 449.99,
      salePrice: 399.99,
      featured: true,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=SoundWeave+Pro',
      specs: { type: 'Headphones', connectivity: 'Wireless' },
    },
    {
      id: 15,
      name: 'Aether Buds Pro',
      category: 'Audio',
      brand: 'Aether',
      price: 279.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Buds+Pro',
      specs: { type: 'Earbuds', connectivity: 'Wireless' },
    },
    {
      id: 68,
      name: 'Apex Studio Monitors',
      category: 'Audio',
      brand: 'Apex',
      price: 799.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Monitors',
      specs: { type: 'Speakers', connectivity: 'Wired' },
    },
    {
      id: 69,
      name: 'Quantum Bass Pods',
      category: 'Audio',
      brand: 'Quantum',
      price: 199.0,
      salePrice: 159.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Bass+Pods',
      specs: { type: 'Earbuds', connectivity: 'Wireless' },
    },
    {
      id: 70,
      name: 'Chrono-Fi Reference',
      category: 'Audio',
      brand: 'Chrono',
      price: 1200.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Chrono-Fi',
      specs: { type: 'Headphones', connectivity: 'Wired' },
    },
    {
      id: 71,
      name: 'NovaSound Bar+',
      category: 'Audio',
      brand: 'Nova',
      price: 599.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=NovaSound+Bar',
      specs: { type: 'Speakers', connectivity: 'Wireless' },
    },
    {
      id: 72,
      name: 'SoundWeave Go',
      category: 'Audio',
      brand: 'SoundWeave',
      price: 149.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=SoundWeave+Go',
      specs: { type: 'Speakers', connectivity: 'Wireless' },
    },
    {
      id: 73,
      name: 'Aether Buds Lite',
      category: 'Audio',
      brand: 'Aether',
      price: 129.0,
      salePrice: 99.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Buds+Lite',
      specs: { type: 'Earbuds', connectivity: 'Wireless' },
    },
    {
      id: 74,
      name: 'Apex DJ Pro',
      category: 'Audio',
      brand: 'Apex',
      price: 350.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+DJ+Pro',
      specs: { type: 'Headphones', connectivity: 'Wired' },
    },
    {
      id: 75,
      name: 'Quantum ANC-3000',
      category: 'Audio',
      brand: 'Quantum',
      price: 499.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+ANC-3000',
      specs: { type: 'Headphones', connectivity: 'Wireless' },
    },
    {
      id: 125,
      name: 'SoundWeave Mini',
      category: 'Audio',
      brand: 'SoundWeave',
      price: 89.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=SoundWeave+Mini',
      specs: { type: 'Speakers', connectivity: 'Wireless' },
    },
    {
      id: 126,
      name: 'Aether Pods Max',
      category: 'Audio',
      brand: 'Aether',
      price: 779.0,
      salePrice: 699.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Pods+Max',
      specs: { type: 'Headphones', connectivity: 'Wireless' },
    },
    {
      id: 127,
      name: 'Apex Surround System',
      category: 'Audio',
      brand: 'Apex',
      price: 1500.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Surround',
      specs: { type: 'Speakers', connectivity: 'Wired' },
    },
    {
      id: 128,
      name: 'Quantum Clear Mic',
      category: 'Audio',
      brand: 'Quantum',
      price: 180.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Mic',
      specs: { type: 'Microphone', connectivity: 'Wired' },
    },
    {
      id: 129,
      name: 'Chrono-Fi Air',
      category: 'Audio',
      brand: 'Chrono',
      price: 399.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Chrono-Fi+Air',
      specs: { type: 'Earbuds', connectivity: 'Wireless' },
    },
    {
      id: 130,
      name: 'NovaVoice Conference Speaker',
      category: 'Audio',
      brand: 'Nova',
      price: 250.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=NovaVoice',
      specs: { type: 'Speakers', connectivity: 'Wireless' },
    },
    {
      id: 131,
      name: 'SoundWeave Studio',
      category: 'Audio',
      brand: 'SoundWeave',
      price: 650.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=SoundWeave+Studio',
      specs: { type: 'Headphones', connectivity: 'Wired' },
    },
    {
      id: 132,
      name: 'Aether Buds Sport',
      category: 'Audio',
      brand: 'Aether',
      price: 199.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Buds+Sport',
      specs: { type: 'Earbuds', connectivity: 'Wireless' },
    },
    {
      id: 133,
      name: 'Apex Boombox 3',
      category: 'Audio',
      brand: 'Apex',
      price: 450.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Boombox',
      specs: { type: 'Speakers', connectivity: 'Wireless' },
    },
    {
      id: 134,
      name: 'Quantum Podcast Kit',
      category: 'Audio',
      brand: 'Quantum',
      price: 400.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Podcast+Kit',
      specs: { type: 'Microphone', connectivity: 'Wired' },
    },
    {
      id: 135,
      name: 'Intel Core i9-14900K',
      category: 'CPUs',
      brand: 'Intel',
      price: 799.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Core+i9-14900K',
      specs: { clockSpeed: '3.2 GHz', coreCount: '24', cache: '36MB' },
    },
    {
      id: 136,
      name: 'AMD Ryzen 9 9950X',
      category: 'CPUs',
      brand: 'AMD',
      price: 950.0,
      salePrice: 899.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Ryzen+9+9950X',
      specs: { clockSpeed: '4.5 GHz', coreCount: '16', cache: '64MB' },
    },
    {
      id: 137,
      name: 'Intel Core i7-14700K',
      category: 'CPUs',
      brand: 'Intel',
      price: 550.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Core+i7-14700K',
      specs: { clockSpeed: '3.4 GHz', coreCount: '20', cache: '33MB' },
    },
    {
      id: 138,
      name: 'AMD Ryzen 7 9800X',
      category: 'CPUs',
      brand: 'AMD',
      price: 650.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Ryzen+7+9800X',
      specs: { clockSpeed: '4.8 GHz', coreCount: '8', cache: '32MB' },
    },
    {
      id: 139,
      name: 'Intel Core i5-14600K',
      category: 'CPUs',
      brand: 'Intel',
      price: 420.0,
      salePrice: 389.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Core+i5-14600K',
      specs: { clockSpeed: '3.5 GHz', coreCount: '14', cache: '24MB' },
    },
    {
      id: 140,
      name: 'AMD Ryzen 5 9600X',
      category: 'CPUs',
      brand: 'AMD',
      price: 380.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Ryzen+5+9600X',
      specs: { clockSpeed: '5.0 GHz', coreCount: '6', cache: '32MB' },
    },
    {
      id: 141,
      name: 'Intel Core i3-14100',
      category: 'CPUs',
      brand: 'Intel',
      price: 180.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Core+i3-14100',
      specs: { clockSpeed: '3.5 GHz', coreCount: '4', cache: '12MB' },
    },
    {
      id: 142,
      name: 'AMD Ryzen 3 9300X',
      category: 'CPUs',
      brand: 'AMD',
      price: 220.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Ryzen+3+9300X',
      specs: { clockSpeed: '4.5 GHz', coreCount: '4', cache: '8MB' },
    },
    {
      id: 143,
      name: 'AMD Threadripper Pro 7995WX',
      category: 'CPUs',
      brand: 'AMD',
      price: 12000.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Threadripper+Pro',
      specs: { clockSpeed: '2.5 GHz', coreCount: '96', cache: '384MB' },
    },
    {
      id: 144,
      name: 'Intel Xeon W9-3495X',
      category: 'CPUs',
      brand: 'Intel',
      price: 7500.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Intel+Xeon+W9',
      specs: { clockSpeed: '1.9 GHz', coreCount: '56', cache: '105MB' },
    },
    {
      id: 145,
      name: 'NVIDIA GeForce RTX 5090',
      category: 'GPUs',
      brand: 'NVIDIA',
      price: 2599.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=RTX+5090',
      specs: { power: '450W', pcie: '5.0' },
    },
    {
      id: 146,
      name: 'NVIDIA GeForce RTX 5080',
      category: 'GPUs',
      brand: 'NVIDIA',
      price: 1699.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=RTX+5080',
      specs: { power: '320W', pcie: '5.0' },
    },
    {
      id: 147,
      name: 'AMD Radeon RX 8900 XTX',
      category: 'GPUs',
      brand: 'AMD',
      price: 1499.0,
      salePrice: 1399.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Radeon+RX+8900XTX',
      specs: { power: '400W', pcie: '5.0' },
    },
    {
      id: 148,
      name: 'NVIDIA GeForce RTX 5070',
      category: 'GPUs',
      brand: 'NVIDIA',
      price: 999.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=RTX+5070',
      specs: { power: '280W', pcie: '5.0' },
    },
    {
      id: 149,
      name: 'AMD Radeon RX 8800 XT',
      category: 'GPUs',
      brand: 'AMD',
      price: 899.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Radeon+RX+8800XT',
      specs: { power: '300W', pcie: '5.0' },
    },
    {
      id: 150,
      name: 'NVIDIA GeForce RTX 5060',
      category: 'GPUs',
      brand: 'NVIDIA',
      price: 650.0,
      salePrice: 599.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=RTX+5060',
      specs: { power: '200W', pcie: '5.0' },
    },
    {
      id: 151,
      name: 'AMD Radeon RX 8700 XT',
      category: 'GPUs',
      brand: 'AMD',
      price: 550.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Radeon+RX+8700XT',
      specs: { power: '230W', pcie: '5.0' },
    },
    {
      id: 152,
      name: 'Intel Arc A770',
      category: 'GPUs',
      brand: 'Intel',
      price: 450.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Intel+Arc+A770',
      specs: { power: '225W', pcie: '4.0' },
    },
    {
      id: 153,
      name: 'NVIDIA RTX 6000 Ada',
      category: 'GPUs',
      brand: 'NVIDIA',
      price: 9000.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=RTX+6000+Ada',
      specs: { power: '300W', pcie: '4.0' },
    },
    {
      id: 154,
      name: 'AMD Radeon Pro W7900',
      category: 'GPUs',
      brand: 'AMD',
      price: 5200.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Radeon+Pro+W7900',
      specs: { power: '295W', pcie: '4.0' },
    },
    {
      id: 155,
      name: 'SeaSonic PRIME TX-1600',
      category: 'PSUs',
      brand: 'SeaSonic',
      price: 599.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=PRIME+TX-1600',
      specs: { wattage: '1600W', modularity: 'Fully Modular', formFactor: 'ATX' },
    },
    {
      id: 156,
      name: 'Corsair AX1600i',
      category: 'PSUs',
      brand: 'Corsair',
      price: 649.99,
      salePrice: 599.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Corsair+AX1600i',
      specs: { wattage: '1600W', modularity: 'Fully Modular', formFactor: 'ATX' },
    },
    {
      id: 157,
      name: 'be quiet! Dark Power 13 1000W',
      category: 'PSUs',
      brand: 'be quiet!',
      price: 349.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Dark+Power+13',
      specs: { wattage: '1000W', modularity: 'Fully Modular', formFactor: 'ATX' },
    },
    {
      id: 158,
      name: 'EVGA SuperNOVA 1000 G7',
      category: 'PSUs',
      brand: 'EVGA',
      price: 299.99,
      salePrice: 269.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=EVGA+1000+G7',
      specs: { wattage: '1000W', modularity: 'Fully Modular', formFactor: 'ATX' },
    },
    {
      id: 159,
      name: 'SeaSonic FOCUS 850W',
      category: 'PSUs',
      brand: 'SeaSonic',
      price: 159.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=SeaSonic+FOCUS',
      specs: { wattage: '850W', modularity: 'Semi-Modular', formFactor: 'ATX' },
    },
    {
      id: 160,
      name: 'Corsair RM850e',
      category: 'PSUs',
      brand: 'Corsair',
      price: 149.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Corsair+RM850e',
      specs: { wattage: '850W', modularity: 'Fully Modular', formFactor: 'ATX' },
    },
    {
      id: 161,
      name: 'be quiet! Pure Power 12 M 750W',
      category: 'PSUs',
      brand: 'be quiet!',
      price: 119.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Pure+Power+12+M',
      specs: { wattage: '750W', modularity: 'Fully Modular', formFactor: 'ATX' },
    },
    {
      id: 162,
      name: 'EVGA 650 BQ',
      category: 'PSUs',
      brand: 'EVGA',
      price: 89.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=EVGA+650+BQ',
      specs: { wattage: '650W', modularity: 'Semi-Modular', formFactor: 'ATX' },
    },
    {
      id: 163,
      name: 'SeaSonic Core 650W',
      category: 'PSUs',
      brand: 'SeaSonic',
      price: 79.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=SeaSonic+Core+650W',
      specs: { wattage: '650W', modularity: 'Non-Modular', formFactor: 'ATX' },
    },
    {
      id: 164,
      name: 'Corsair SF750',
      category: 'PSUs',
      brand: 'Corsair',
      price: 189.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Corsair+SF750',
      specs: { wattage: '750W', modularity: 'Fully Modular', formFactor: 'SFX' },
    },
    {
      id: 7,
      name: 'ErgoMech Keyboard Pro',
      category: 'Keyboards',
      brand: 'ErgoMech',
      price: 229.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=ErgoMech+Pro',
      specs: { size: 'Split', switchType: 'Mechanical' },
    },
    {
      id: 82,
      name: 'Chrono Pro Keyboard',
      category: 'Keyboards',
      brand: 'Chrono',
      price: 189.0,
      salePrice: 169.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Chrono+Pro',
      specs: { size: 'Full-size', switchType: 'Mechanical' },
    },
    {
      id: 165,
      name: 'Apex Pro TKL',
      category: 'Keyboards',
      brand: 'Apex',
      price: 249.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Pro+TKL',
      specs: { size: 'TKL', switchType: 'Mechanical' },
    },
    {
      id: 166,
      name: 'Logi MX Keys S',
      category: 'Keyboards',
      brand: 'Logi',
      price: 149.99,
      salePrice: 129.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Logi+MX+Keys',
      specs: { size: 'Full-size', switchType: 'Membrane' },
    },
    {
      id: 167,
      name: 'QuantumForce Mechanical',
      category: 'Keyboards',
      brand: 'Quantum',
      price: 179.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=QuantumForce',
      specs: { size: 'TKL', switchType: 'Mechanical' },
    },
    {
      id: 168,
      name: 'Aether Scribe',
      category: 'Keyboards',
      brand: 'Aether',
      price: 199.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Scribe',
      specs: { size: '75%', switchType: 'Mechanical' },
    },
    {
      id: 169,
      name: 'Nova Type-C Compact',
      category: 'Keyboards',
      brand: 'Nova',
      price: 89.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Nova+Compact',
      specs: { size: '60%', switchType: 'Mechanical' },
    },
    {
      id: 170,
      name: 'ErgoMech Split KB Lite',
      category: 'Keyboards',
      brand: 'ErgoMech',
      price: 199.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=ErgoMech+Lite',
      specs: { size: 'Split', switchType: 'Mechanical' },
    },
    {
      id: 171,
      name: 'Chrono-Gamer Elite',
      category: 'Keyboards',
      brand: 'Chrono',
      price: 210.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Chrono-Gamer',
      specs: { size: 'Full-size', switchType: 'Mechanical' },
    },
    {
      id: 172,
      name: 'Logi Wave Keys',
      category: 'Keyboards',
      brand: 'Logi',
      price: 79.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Logi+Wave',
      specs: { size: 'Full-size', switchType: 'Membrane' },
    },
    {
      id: 76,
      name: 'Apex Pro Gaming Mouse',
      category: 'Mice',
      brand: 'Apex',
      price: 149.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Pro+Mouse',
      specs: { connectivity: 'Wireless' },
    },
    {
      id: 79,
      name: 'Logi Master Mouse MX5',
      category: 'Mice',
      brand: 'Logi',
      price: 129.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Logi+MX5',
      specs: { connectivity: 'Wireless' },
    },
    {
      id: 173,
      name: 'Quantum Catalyst Pro',
      category: 'Mice',
      brand: 'Quantum',
      price: 119.0,
      salePrice: 99.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Catalyst',
      specs: { connectivity: 'Wireless' },
    },
    {
      id: 174,
      name: 'Aether Precision Mouse',
      category: 'Mice',
      brand: 'Aether',
      price: 99.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Precision',
      specs: { connectivity: 'Wireless' },
    },
    {
      id: 175,
      name: 'ChronoGrip Vertical',
      category: 'Mice',
      brand: 'Chrono',
      price: 85.0,
      salePrice: 69.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=ChronoGrip',
      specs: { connectivity: 'Wired' },
    },
    {
      id: 176,
      name: 'Nova Wireless Mouse',
      category: 'Mice',
      brand: 'Nova',
      price: 49.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Nova+Wireless',
      specs: { connectivity: 'Wireless' },
    },
    {
      id: 177,
      name: 'Apex Venom Air',
      category: 'Mice',
      brand: 'Apex',
      price: 189.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Apex+Venom+Air',
      specs: { connectivity: 'Wireless' },
    },
    {
      id: 178,
      name: 'Logi Lift Vertical',
      category: 'Mice',
      brand: 'Logi',
      price: 89.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Logi+Lift',
      specs: { connectivity: 'Wireless' },
    },
    {
      id: 179,
      name: 'Quantum Ion Mouse',
      category: 'Mice',
      brand: 'Quantum',
      price: 79.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Quantum+Ion',
      specs: { connectivity: 'Wired' },
    },
    {
      id: 180,
      name: 'Aether Sculpt Mouse',
      category: 'Mice',
      brand: 'Aether',
      price: 110.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aether+Sculpt',
      specs: { connectivity: 'Wired' },
    },
    {
      id: 181,
      name: 'Corsair Vengeance 32GB',
      category: 'RAM',
      brand: 'Corsair',
      price: 189.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Vengeance+32GB',
      specs: { capacity: '32GB', ddrVersion: 'DDR5' },
    },
    {
      id: 182,
      name: 'G.Skill Trident Z5 32GB',
      category: 'RAM',
      brand: 'G.Skill',
      price: 219.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Trident+Z5+32GB',
      specs: { capacity: '32GB', ddrVersion: 'DDR5' },
    },
    {
      id: 183,
      name: 'Kingston Fury Beast 16GB',
      category: 'RAM',
      brand: 'Kingston',
      price: 89.99,
      salePrice: 79.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Fury+Beast+16GB',
      specs: { capacity: '16GB', ddrVersion: 'DDR5' },
    },
    {
      id: 184,
      name: 'Crucial Pro 32GB',
      category: 'RAM',
      brand: 'Crucial',
      price: 159.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Crucial+Pro+32GB',
      specs: { capacity: '32GB', ddrVersion: 'DDR5' },
    },
    {
      id: 185,
      name: 'Corsair Dominator Platinum 64GB',
      category: 'RAM',
      brand: 'Corsair',
      price: 450.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Dominator+64GB',
      specs: { capacity: '64GB', ddrVersion: 'DDR5' },
    },
    {
      id: 186,
      name: 'G.Skill Ripjaws S5 32GB',
      category: 'RAM',
      brand: 'G.Skill',
      price: 170.0,
      salePrice: 149.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Ripjaws+S5+32GB',
      specs: { capacity: '32GB', ddrVersion: 'DDR5' },
    },
    {
      id: 187,
      name: 'Kingston ValueRAM 8GB',
      category: 'RAM',
      brand: 'Kingston',
      price: 45.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=ValueRAM+8GB',
      specs: { capacity: '8GB', ddrVersion: 'DDR4' },
    },
    {
      id: 188,
      name: 'Crucial Ballistix 16GB',
      category: 'RAM',
      brand: 'Crucial',
      price: 75.0,
      salePrice: 59.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Ballistix+16GB',
      specs: { capacity: '16GB', ddrVersion: 'DDR4' },
    },
    {
      id: 189,
      name: 'Corsair Vengeance LPX 16GB',
      category: 'RAM',
      brand: 'Corsair',
      price: 69.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Vengeance+LPX',
      specs: { capacity: '16GB', ddrVersion: 'DDR4' },
    },
    {
      id: 190,
      name: 'G.Skill Aegis 16GB',
      category: 'RAM',
      brand: 'G.Skill',
      price: 65.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Aegis+16GB',
      specs: { capacity: '16GB', ddrVersion: 'DDR4' },
    },
    {
      id: 191,
      name: 'Kingston Fury Renegade 64GB',
      category: 'RAM',
      brand: 'Kingston',
      price: 399.0,
      salePrice: 349.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Fury+Renegade+64GB',
      specs: { capacity: '64GB', ddrVersion: 'DDR5' },
    },
    {
      id: 192,
      name: 'Crucial 8GB Laptop SODIMM',
      category: 'RAM',
      brand: 'Crucial',
      price: 50.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Crucial+SODIMM',
      specs: { capacity: '8GB', ddrVersion: 'DDR4' },
    },
    {
      id: 193,
      name: 'Corsair Vengeance 64GB',
      category: 'RAM',
      brand: 'Corsair',
      price: 350.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Vengeance+64GB',
      specs: { capacity: '64GB', ddrVersion: 'DDR5' },
    },
    {
      id: 194,
      name: 'G.Skill Trident Z Royal 32GB',
      category: 'RAM',
      brand: 'G.Skill',
      price: 250.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Trident+Z+Royal',
      specs: { capacity: '32GB', ddrVersion: 'DDR4' },
    },
    {
      id: 195,
      name: 'Kingston Fury Impact 32GB SODIMM',
      category: 'RAM',
      brand: 'Kingston',
      price: 180.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Fury+Impact+32GB',
      specs: { capacity: '32GB', ddrVersion: 'DDR5' },
    },
    {
      id: 196,
      name: 'Crucial 32GB Kit (2x16GB)',
      category: 'RAM',
      brand: 'Crucial',
      price: 150.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Crucial+32GB+Kit',
      specs: { capacity: '32GB', ddrVersion: 'DDR4' },
    },
    {
      id: 197,
      name: 'Corsair Vengeance RGB 32GB',
      category: 'RAM',
      brand: 'Corsair',
      price: 199.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Vengeance+RGB',
      specs: { capacity: '32GB', ddrVersion: 'DDR5' },
    },
    {
      id: 198,
      name: 'G.Skill Flare X5 32GB',
      category: 'RAM',
      brand: 'G.Skill',
      price: 165.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Flare+X5+32GB',
      specs: { capacity: '32GB', ddrVersion: 'DDR5' },
    },
    {
      id: 199,
      name: 'Kingston Beast RGB 32GB',
      category: 'RAM',
      brand: 'Kingston',
      price: 180.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Beast+RGB+32GB',
      specs: { capacity: '32GB', ddrVersion: 'DDR5' },
    },
    {
      id: 200,
      name: 'Crucial Pro 64GB Kit (2x32GB)',
      category: 'RAM',
      brand: 'Crucial',
      price: 299.0,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Crucial+Pro+64GB',
      specs: { capacity: '64GB', ddrVersion: 'DDR5' },
    },
  ])

  const cart = ref([])
  const uiStore = useUIStore()

  const cartItemCount = computed(() => {
    return cart.value.reduce((acc, item) => acc + item.quantity, 0)
  })

  const cartTotal = computed(() => {
    return cart.value.reduce((acc, item) => {
      const price = item.salePrice || item.price
      return acc + price * item.quantity
    }, 0)
  })

  const cartSavings = computed(() => {
    return cart.value.reduce((acc, item) => {
      if (item.salePrice) {
        return acc + (item.price - item.salePrice) * item.quantity
      }
      return acc
    }, 0)
  })

  function addToCart(productId) {
    const product = products.value.find((p) => p.id === productId)
    if (!product) return

    const cartItem = cart.value.find((item) => item.id === productId)
    if (cartItem) {
      cartItem.quantity++
    } else {
      cart.value.push({ ...product, quantity: 1 })
    }
    uiStore.showNotification(`${product.name} added to cart!`)
  }

  function removeFromCart(productId) {
    const index = cart.value.findIndex((item) => item.id === productId)
    if (index !== -1) {
      cart.value.splice(index, 1)
    }
  }

  function updateQuantity(productId, quantity) {
    const cartItem = cart.value.find((item) => item.id === productId)
    if (cartItem) {
      if (quantity > 0) {
        cartItem.quantity = quantity
      } else {
        removeFromCart(productId)
      }
    }
  }

  function clearCart() {
    cart.value = []
  }

  return {
    products,
    cart,
    addToCart,
    removeFromCart,
    updateQuantity,
    clearCart,
    cartItemCount,
    cartTotal,
    cartSavings,
  }
})
