import { ref, computed } from 'vue'
import { defineStore } from 'pinia'
import { useUIStore } from './ui'

export const useProductStore = defineStore('products', () => {
  const products = ref([
    // Laptops (20)
    {
      id: 1,
      name: 'Apple MacBook Pro 14"',
      category: 'Laptops',
      brand: 'Apple',
      price: 2899.99,
      salePrice: 2699.99,
      featured: true,
      imageUrl:
        'https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/1.webp',
      specs: { ram: '16GB', cpu: 'Intel Core i9', storage: '1TB SSD', screenSize: '14"' },
    },
    {
      id: 8,
      name: 'Asus Zenbook Pro Dual"',
      category: 'Laptops',
      brand: 'Asus',
      price: 1799.0,
      imageUrl:
        'https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/1.webp',
      specs: { ram: '16GB', cpu: 'Intel Core i7', storage: '512GB SSD', screenSize: '14"' },
    },
    {
      id: 16,
      name: 'Huawei Matebook X Pro',
      category: 'Laptops',
      brand: 'Huawei',
      price: 3499.0,
      salePrice: 3299.0,
      featured: true,
      imageUrl: 'https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/1.webp',
      specs: { ram: '32GB', cpu: 'AMD Ryzen 9', storage: '2TB SSD', screenSize: '17"' },
    },
    {
      id: 17,
      name: 'Lenovo Yoga 920',
      category: 'Laptops',
      brand: 'Lenovo',
      price: 4200.0,
      imageUrl: 'https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/1.webp',
      specs: { ram: '64GB', cpu: 'Intel Core i9', storage: '4TB SSD', screenSize: '15.6"' },
    },
    {
      id: 18,
      name: 'XPS 13 9300 Laptop"',
      category: 'Laptops',
      brand: 'Dell',
      price: 1299.0,
      salePrice: 1149.0,
      imageUrl:
        'https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/1.webp',
      specs: { ram: '8GB', cpu: 'Intel Core i5', storage: '256GB SSD', screenSize: '13.3"' },
    },
    {
      id: 28,
      name: 'Surface Latop',
      category: 'Laptops',
      brand: 'Microsoft',
      price: 2199.99,
      imageUrl: 'https://i.imgur.com/ymZoOoX.jpeg',
      specs: { ram: '16GB', cpu: 'AMD Ryzen 7', storage: '1TB SSD', screenSize: '15.6"' },
    },
    {
      id: 29,
      name: 'ZenBook 14 OLED',
      category: 'Laptops',
      brand: 'Asus',
      price: 3899.0,
      imageUrl: 'https://i.imgur.com/Uoi4ims.jpeg',
      specs: { ram: '32GB', cpu: 'Intel Core i9', storage: '2TB SSD', screenSize: '14"' },
    },
    {
      id: 30,
      name: 'Yoga Slim 7x',
      category: 'Laptops',
      brand: 'Lenovo',
      price: 1599.0,
      salePrice: 1399.0,
      imageUrl: 'https://i.imgur.com/cGuZKgz.jpeg',
      specs: { ram: '16GB', cpu: 'Intel Core i7', storage: '1TB SSD', screenSize: '13.4"' },
    },
    {
      id: 31,
      name: 'ASUS Zenbook A14',
      category: 'Laptops',
      brand: 'Asus',
      price: 1450.0,
      imageUrl: 'https://i.imgur.com/cSQteh7.jpeg',
      specs: { ram: '8GB', cpu: 'AMD Ryzen 5', storage: '512GB SSD', screenSize: '14"' },
    },
    {
      id: 32,
      name: 'IdeaPad Slim 3"',
      category: 'Laptops',
      brand: 'Lenovo',
      price: 2599.0,
      imageUrl: 'https://i.imgur.com/hCkkzDq.jpeg',
      specs: { ram: '16GB', cpu: 'Intel Core i7', storage: '1TB SSD', screenSize: '14"' },
    },
    {
      id: 85,
      name: 'Inspiron 15',
      category: 'Laptops',
      brand: 'Dell',
      price: 2899.0,
      imageUrl: 'https://i.imgur.com/tUf5NWx.jpeg',
      specs: { ram: '32GB', cpu: 'AMD Ryzen 7', storage: '1TB SSD', screenSize: '15"' },
    },
    {
      id: 86,
      name: 'Vivobook 16',
      category: 'Laptops',
      brand: 'Asus',
      price: 4800.0,
      imageUrl: 'https://i.imgur.com/WpwGblS.jpeg',
      specs: { ram: '64GB', cpu: 'Intel Core i9', storage: '2TB SSD', screenSize: '16"' },
    },
    {
      id: 87,
      name: 'IdeaPad 3',
      category: 'Laptops',
      brand: 'Lenovo',
      price: 1999.0,
      imageUrl: 'https://i.imgur.com/TRYUOgc.jpeg',
      specs: { ram: '16GB', cpu: 'Intel Core i7', storage: '1TB SSD', screenSize: '15.6"' },
    },
    {
      id: 88,
      name: 'ProBook 445 14',
      category: 'Laptops',
      brand: 'HP',
      price: 1650.0,
      salePrice: 1450.0,
      imageUrl: 'https://i.imgur.com/BKk7WY0.jpeg',
      specs: { ram: '16GB', cpu: 'AMD Ryzen 7', storage: '512GB SSD', screenSize: '14"' },
    },
    {
      id: 89,
      name: 'Vivobook 16',
      category: 'Laptops',
      brand: 'Asus',
      price: 1899.0,
      imageUrl: 'https://i.imgur.com/bGIXUkr.jpeg',
      specs: { ram: '16GB', cpu: 'Intel Core i5', storage: '1TB SSD', screenSize: '16"' },
    },
    {
      id: 90,
      name: 'Inspiron 15',
      category: 'Laptops',
      brand: 'Dell',
      price: 1999.0,
      imageUrl: 'https://i.imgur.com/4D0pZqt.jpeg',
      specs: { ram: '16GB', cpu: 'Intel Core i7', storage: '1TB SSD', screenSize: '15.6"' },
    },
    {
      id: 91,
      name: 'MacBook Pro 16',
      category: 'Laptops',
      brand: 'Apple',
      price: 1350.0,
      imageUrl: 'https://i.imgur.com/SNV2HkM.jpeg',
      specs: { ram: '8GB', cpu: 'Intel Core i5', storage: '512GB SSD', screenSize: '16"' },
    },
    {
      id: 92,
      name: ' IdeaPad 1i',
      category: 'Laptops',
      brand: 'Lenovo',
      price: 3200.0,
      imageUrl: 'https://i.imgur.com/md0VJYi.jpeg',
      specs: { ram: '32GB', cpu: 'Intel Core i9', storage: '1TB SSD', screenSize: '17"' },
    },
    {
      id: 93,
      name: 'MacBook Air 16"',
      category: 'Laptops',
      brand: 'Apple',
      price: 2200.0,
      imageUrl: 'https://i.imgur.com/10b2M74.jpeg',
      specs: { ram: '32GB', cpu: 'AMD Ryzen 7', storage: '1TB SSD', screenSize: '16"' },
    },
    {
      id: 94,
      name: 'MacBook Air 13"',
      category: 'Laptops',
      brand: 'Apple',
      price: 999.0,
      imageUrl: 'https://i.imgur.com/BUfiU5n.jpeg',
      specs: { ram: '8GB', cpu: 'Intel Core i3', storage: '256GB SSD', screenSize: '13.3"' },
    },
    {
      id: 2,
      name: 'iPhone 14 Pro',
      category: 'Smartphones',
      brand: 'Apple',
      price: 1599.0,
      salePrice: 1499.0,
      featured: true,
      imageUrl: 'https://i.imgur.com/o7CP0Tp.jpeg',
      specs: { storage: '256GB' },
    },
    {
      id: 9,
      name: 'iPhone 16 Pro Max',
      category: 'Smartphones',
      brand: 'Apple',
      price: 899.0,
      salePrice: 799.0,
      imageUrl: 'https://i.imgur.com/dx4QH1D.jpeg',
      specs: { storage: '128GB' },
    },
    {
      id: 19,
      name: 'iPhone 14 Pro',
      category: 'Smartphones',
      brand: 'Apple',
      price: 1399.0,
      imageUrl: 'https://i.imgur.com/p3GKTlt.png',
      specs: { storage: '512GB' },
    },
    {
      id: 20,
      name: 'Apple iPhone 16',
      category: 'Smartphones',
      brand: 'Apple',
      price: 1899.0,
      imageUrl: 'https://i.imgur.com/Cjeav0x.jpeg',
      specs: { storage: '1TB' },
    },
    {
      id: 33,
      name: 'iPhone 13',
      category: 'Smartphones',
      brand: 'Apple',
      price: 1199.0,
      salePrice: 1049.0,
      imageUrl: 'https://i.imgur.com/Mp09Kp3.jpeg',
      specs: { storage: '256GB' },
    },
    {
      id: 34,
      name: 'iPhone 14 Pro',
      category: 'Smartphones',
      brand: 'Apple',
      price: 699.0,
      imageUrl: 'https://i.imgur.com/tVazL5H.jpeg',
      specs: { storage: '128GB' },
    },
    {
      id: 35,
      name: 'iPhone 14',
      category: 'Smartphones',
      brand: 'Apple',
      price: 2199.0,
      imageUrl: 'https://i.imgur.com/CzHy3Ub.jpeg',
      specs: { storage: '512GB' },
    },
    {
      id: 36,
      name: 'Galaxy S22 Ultra 5G',
      category: 'Smartphones',
      brand: 'Samsung',
      price: 999.0,
      imageUrl: 'https://i.imgur.com/NHT8Tp6.jpeg',
      specs: { storage: '256GB' },
    },
    {
      id: 37,
      name: 'Galaxy S22 Ultra 5G',
      category: 'Smartphones',
      brand: 'Samsung',
      price: 2099.0,
      salePrice: 1899.0,
      imageUrl: 'https://i.imgur.com/1pAnlYS.jpeg',
      specs: { storage: '1TB' },
    },
    {
      id: 38,
      name: 'Galaxy Z Flip5 5G',
      category: 'Smartphones',
      brand: 'Samsung',
      price: 1750.0,
      imageUrl: 'https://i.imgur.com/DTRN3Uc.jpeg',
      specs: { storage: '512GB' },
    },
    {
      id: 95,
      name: 'OnePlus 12 5G',
      category: 'Smartphones',
      brand: 'OnePlus',
      price: 850.0,
      imageUrl: 'https://i.imgur.com/9qxtYG4.jpeg',
      specs: { storage: '256GB' },
    },
    {
      id: 96,
      name: 'Galaxy Z Fold3 5G',
      category: 'Smartphones',
      brand: 'Samsung',
      price: 750.0,
      imageUrl: 'https://i.imgur.com/RsAZifW.jpeg',
      specs: { storage: '128GB' },
    },
    {
      id: 97,
      name: 'Galaxy Z Fold5',
      category: 'Smartphones',
      brand: 'Samsung',
      price: 1999.0,
      imageUrl: 'https://i.imgur.com/D77Obn8.jpeg',
      specs: { storage: '1TB' },
    },
    {
      id: 98,
      name: 'OnePlus 12 5G',
      category: 'Smartphones',
      brand: 'Oneplus',
      price: 1099.0,
      imageUrl: 'https://i.imgur.com/BJdJjKm.jpeg',
      specs: { storage: '256GB' },
    },
    {
      id: 99,
      name: 'Pixel 9 Pro XL',
      category: 'Smartphones',
      brand: 'Google',
      price: 1300.0,
      imageUrl: 'https://i.imgur.com/wZkecrs.jpeg',
      specs: { storage: '256GB' },
    },
    {
      id: 100,
      name: ' Galaxy Z Fold 4 5G',
      category: 'Smartphones',
      brand: 'Samsung',
      price: 499.0,
      imageUrl: 'https://i.imgur.com/bWy2uOJ.png',
      specs: { storage: '64GB' },
    },
    {
      id: 101,
      name: 'Samsung Galaxy Z Fold4 5G',
      category: 'Smartphones',
      brand: 'Samsung',
      price: 1599.0,
      imageUrl: 'https://i.imgur.com/WynSrfL.jpeg',
      specs: { storage: '512GB' },
    },
    {
      id: 102,
      name: 'Google Pixel 9',
      category: 'Smartphones',
      brand: 'Google',
      price: 1400.0,
      imageUrl: 'https://i.imgur.com/SfURn89.jpeg',
      specs: { storage: '256GB' },
    },
    {
      id: 103,
      name: 'Google Pixel 7',
      category: 'Smartphones',
      brand: 'Google',
      price: 1250.0,
      imageUrl: 'https://i.imgur.com/GzwMWn6.jpeg',
      specs: { storage: '128GB' },
    },
    {
      id: 104,
      name: 'Google Pixel 7 Pro',
      category: 'Smartphones',
      brand: 'Google',
      price: 1550.0,
      imageUrl: 'https://i.imgur.com/B3PJMvM.jpeg',
      specs: { storage: '256GB' },
    },
    {
      id: 14,
      name: 'Aegis ZS2',
      category: 'Desktops',
      brand: 'MSI',
      price: 3250.0,
      imageUrl: 'https://i.imgur.com/fJr0EwW.png',
      specs: { ram: '32GB', cpu: 'Intel Core i7', storage: '1TB SSD + 2TB HDD' },
    },
    {
      id: 23,
      name: 'Legion Tower 7i',
      category: 'Desktops',
      brand: 'Lenovo',
      price: 4500.0,
      salePrice: 4250.0,
      featured: true,
      imageUrl: 'https://i.imgur.com/AWtXdaL.jpeg',
      specs: { ram: '32GB', cpu: 'AMD Ryzen 9', storage: '2TB SSD' },
    },
    {
      id: 24,
      name: 'Gamer Supreme',
      category: 'Desktops',
      brand: 'CyberPower',
      price: 1499.0,
      imageUrl: 'https://i.imgur.com/pvIANSZ.jpeg',
      specs: { ram: '16GB', cpu: 'Intel Core i5', storage: '512GB SSD' },
    },
    {
      id: 46,
      name: 'Legion Tower 5',
      category: 'Desktops',
      brand: 'Lenovo',
      price: 5500.0,
      imageUrl: 'https://i.imgur.com/E4PwWXz.jpeg',
      specs: { ram: '64GB', cpu: 'Intel Core i9', storage: '4TB SSD' },
    },
    {
      id: 47,
      name: 'Gamer Supreme',
      category: 'Desktops',
      brand: 'CyberPower',
      price: 1100.0,
      salePrice: 950.0,
      imageUrl: 'https://i.imgur.com/nt845E6.jpeg',
      specs: { ram: '16GB', cpu: 'AMD Ryzen 5', storage: '512GB SSD' },
    },
    {
      id: 48,
      name: 'Aegis Gaming 557',
      category: 'Desktops',
      brand: 'MSI',
      price: 2999.0,
      imageUrl: 'https://i.imgur.com/VrAs2Z0.jpeg',
      specs: { ram: '32GB', cpu: 'Intel Core i7', storage: '1TB SSD' },
    },
    {
      id: 49,
      name: 'ROG G700',
      category: 'Desktops',
      brand: 'Asus',
      price: 2499.0,
      salePrice: 2299.0,
      imageUrl: 'https://i.imgur.com/czgTivQ.jpeg',
      specs: { ram: '16GB', cpu: 'Intel Core i7', storage: '1TB SSD' },
    },
    {
      id: 50,
      name: 'Gamer Xtreme',
      category: 'Desktops',
      brand: 'CyberPower',
      price: 999.0,
      imageUrl: 'https://i.imgur.com/rbjl0qt.jpeg',
      specs: { ram: '8GB', cpu: 'Intel Core i3', storage: '256GB SSD' },
    },
    {
      id: 51,
      name: 'ROG G705',
      category: 'Desktops',
      brand: 'Asus',
      price: 6200.0,
      imageUrl: 'https://i.imgur.com/lfjz9GI.jpeg',
      specs: { ram: '64GB', cpu: 'AMD Ryzen 9', storage: '4TB SSD' },
    },
    {
      id: 52,
      name: 'Codex R2',
      category: 'Desktops',
      brand: 'MSI',
      price: 1999.0,
      salePrice: 1799.0,
      imageUrl: 'https://i.imgur.com/qgOtBfh.jpeg',
      specs: { ram: '16GB', cpu: 'AMD Ryzen 7', storage: '1TB SSD' },
    },
    {
      id: 115,
      name: 'Gamer Master',
      category: 'Desktops',
      brand: 'CyberPower',
      price: 3800.0,
      imageUrl: 'https://i.imgur.com/vR7IlSc.jpeg',
      specs: { ram: '32GB', cpu: 'Intel Core i9', storage: '2TB SSD' },
    },
    {
      id: 116,
      name: 'ROG Strix G13',
      category: 'Desktops',
      brand: 'Asus',
      price: 850.0,
      imageUrl: 'https://i.imgur.com/UbiJg3s.jpeg',
      specs: { ram: '8GB', cpu: 'Intel Core i5', storage: '512GB SSD' },
    },
    {
      id: 117,
      name: 'Legion Tower 6i',
      category: 'Desktops',
      brand: 'Aether',
      price: 4100.0,
      imageUrl: 'https://i.imgur.com/ZbS5coN.jpeg',
      specs: { ram: '64GB', cpu: 'Intel Core i9', storage: '2TB SSD' },
    },
    {
      id: 118,
      name: 'Codex R3',
      category: 'Desktops',
      brand: 'MSI',
      price: 6800.0,
      imageUrl: 'https://i.imgur.com/Uz7nGwq.jpeg',
      specs: { ram: '128GB', cpu: 'AMD Threadripper', storage: '4TB SSD' },
    },
    {
      id: 119,
      name: 'OMEN 16L',
      category: 'Desktops',
      brand: 'HP',
      price: 2800.0,
      imageUrl: 'https://i.imgur.com/irk8M3F.jpeg',
      specs: { ram: '32GB', cpu: 'AMD Ryzen 7', storage: '1TB SSD' },
    },
    {
      id: 120,
      name: 'Omen 35L',
      category: 'Desktops',
      brand: 'HP',
      price: 3100.0,
      imageUrl: 'https://i.imgur.com/MQkErhj.jpeg',
      specs: { ram: '32GB', cpu: 'Intel Core i7', storage: '1TB SSD' },
    },
    {
      id: 121,
      name: 'TUF Gaming T500',
      category: 'Desktops',
      brand: 'Asus',
      price: 1750.0,
      imageUrl: 'https://i.imgur.com/axqx2hA.jpeg',
      specs: { ram: '16GB', cpu: 'Intel Core i7', storage: '1TB SSD' },
    },
    {
      id: 135,
      name: 'Intel Core i5-14600K',
      category: 'CPUs',
      brand: 'Intel',
      price: 799.0,
      imageUrl: 'https://i.imgur.com/QAGf1n9.jpeg',
      specs: { clockSpeed: '3.2 GHz', coreCount: '24', cache: '32MB' },
    },
    {
      id: 136,
      name: 'AMD Ryzen 9 9950X',
      category: 'CPUs',
      brand: 'AMD',
      price: 950.0,
      salePrice: 899.0,
      imageUrl: 'https://i.imgur.com/lD3DzfA.jpeg',
      specs: { clockSpeed: '4.6 GHz', coreCount: '16', cache: '64MB' },
    },
    {
      id: 137,
      name: 'Intel Core i7-14700K',
      category: 'CPUs',
      brand: 'Intel',
      price: 550.0,
      imageUrl: 'https://i.imgur.com/8KbwePG.png',
      specs: { clockSpeed: '3.2 GHz', coreCount: '20', cache: '32MB' },
    },
    {
      id: 138,
      name: 'AMD Ryzen 7 9800X3D',
      category: 'CPUs',
      brand: 'AMD',
      price: 650.0,
      imageUrl: 'https://i.imgur.com/iIXTr23.jpeg',
      specs: { clockSpeed: '4.6 GHz', coreCount: '8', cache: '32MB' },
    },
    {
      id: 139,
      name: 'Intel Core Ultra 9-285K',
      category: 'CPUs',
      brand: 'Intel',
      price: 420.0,
      salePrice: 389.0,
      imageUrl: 'https://i.imgur.com/ElE1AwF.jpeg',
      specs: { clockSpeed: '3.2 GHz', coreCount: '14', cache: '24MB' },
    },
    {
      id: 140,
      name: 'AMD Ryzen 7 5700',
      category: 'CPUs',
      brand: 'AMD',
      price: 380.0,
      imageUrl: 'https://i.imgur.com/W10DnkM.jpeg',
      specs: { clockSpeed: '5.0 GHz', coreCount: '6', cache: '32MB' },
    },
    {
      id: 141,
      name: 'AMD Ryzen 7 7800X3D',
      category: 'CPUs',
      brand: 'AMD',
      price: 180.0,
      imageUrl: 'https://i.imgur.com/f1oiXNk.png',
      specs: { clockSpeed: '3.2 GHz', coreCount: '4', cache: '12MB' },
    },
    {
      id: 142,
      name: 'AMD Ryzen 5 9600X',
      category: 'CPUs',
      brand: 'AMD',
      price: 220.0,
      imageUrl: 'https://i.imgur.com/94WvsRT.png',
      specs: { clockSpeed: '4.6 GHz', coreCount: '4', cache: '8MB' },
    },
    {
      id: 143,
      name: 'AMD Ryzen 9 9950X3D',
      category: 'CPUs',
      brand: 'AMD',
      price: 1200.0,
      imageUrl: 'https://i.imgur.com/fi4nAeO.jpeg',
      specs: { clockSpeed: '3.2 GHz', coreCount: '96', cache: '384MB' },
    },
    {
      id: 144,
      name: 'AMD Ryzen 5 5600GT',
      category: 'CPUs',
      brand: 'AMD',
      price: 750.0,
      imageUrl: 'https://i.imgur.com/j9ocv4n.jpeg',
      specs: { clockSpeed: '3.2 GHz', coreCount: '56', cache: '105MB' },
    },
    {
      id: 145,
      name: 'ROG Astral GeForce RTX 5090 OC',
      category: 'GPUs',
      brand: 'NVIDIA',
      price: 2599.0,
      imageUrl: 'https://i.imgur.com/d5S97t1.jpeg',
      specs: { power: '450W', pcie: '5.0' },
    },
    {
      id: 146,
      name: 'GeForce RTX 5080',
      category: 'GPUs',
      brand: 'NVIDIA',
      price: 1699.0,
      imageUrl: 'https://i.imgur.com/mcbkoY3.png',
      specs: { power: '320W', pcie: '5.0' },
    },
    {
      id: 147,
      name: 'Radeon RX 9070 XT',
      category: 'GPUs',
      brand: 'AMD',
      price: 1499.0,
      salePrice: 1399.0,
      imageUrl: 'https://i.imgur.com/KyxhgMM.jpeg',
      specs: { power: '400W', pcie: '5.0' },
    },
    {
      id: 148,
      name: 'NVIDIA GeForce RTX 5070',
      category: 'GPUs',
      brand: 'NVIDIA',
      price: 999.0,
      imageUrl: 'https://i.imgur.com/gipamIF.png',
      specs: { power: '280W', pcie: '5.0' },
    },
    {
      id: 149,
      name: 'GeForce RTX 5070',
      category: 'GPUs',
      brand: 'NVIDIA',
      price: 899.0,
      imageUrl: 'https://i.imgur.com/xjKgx5Q.png',
      specs: { power: '300W', pcie: '5.0' },
    },
    {
      id: 150,
      name: 'TUF Gaming GeForce RTX 5070 OC',
      category: 'GPUs',
      brand: 'NVIDIA',
      price: 650.0,
      salePrice: 599.0,
      imageUrl: 'https://i.imgur.com/myrVyjv.jpeg',
      specs: { power: '200W', pcie: '5.0' },
    },
    {
      id: 151,
      name: 'GeForce RTX 5070 AMP',
      category: 'GPUs',
      brand: 'NVIDIA',
      price: 550.0,
      imageUrl: 'https://i.imgur.com/waftBPk.png',
      specs: { power: '230W', pcie: '5.0' },
    },
    {
      id: 152,
      name: 'GeForce RTX 5070 Gaming Trio OC',
      category: 'GPUs',
      brand: 'NVIDIA',
      price: 450.0,
      imageUrl: 'https://i.imgur.com/3pVGXvG.jpeg',
      specs: { power: '225W', pcie: '4.0' },
    },
    {
      id: 153,
      name: 'GeForce RTX 5070 Solid OC',
      category: 'GPUs',
      brand: 'NVIDIA',
      price: 900.0,
      imageUrl: 'https://i.imgur.com/KXmTwCk.png',
      specs: { power: '300W', pcie: '4.0' },
    },
    {
      id: 7,
      name: 'U8000F Series 4K UHD HDR LED Tizen Smart TV',
      category: 'TV',
      brand: 'Samsung',
      price: 2299.0,
      imageUrl: 'https://i.imgur.com/1X5oaKG.jpeg',
      specs: { size: '65"' },
    },
    {
      id: 82,
      name: 'Bravia XR 65" X90L Series',
      category: 'TV',
      brand: 'Sony',
      price: 1890.0,
      salePrice: 1699.0,
      imageUrl: 'https://i.imgur.com/gVGbzP9.jpeg',
      specs: { size: '65"' },
    },
    {
      id: 165,
      name: 'Samsung 75" 4K UHD HDR QLED Tizen Smart TV',
      category: 'TV',
      brand: 'Sausung',
      price: 2409.99,
      imageUrl: 'https://i.imgur.com/k95BfyW.jpeg',
      specs: { size: '75"' },
    },
    {
      id: 166,
      name: 'Bravia 8 65" XR80 Series 4K UHD HDR OLED',
      category: 'TV',
      brand: 'Sony',
      price: 2149.99,
      salePrice: 1290.99,
      imageUrl: 'https://i.imgur.com/OX4RMJk.jpeg',
      specs: { size: '65"' },
    },
    {
      id: 167,
      name: 'Samsung 75" 4K UHD HDR Neo QLED Tizen Smart TV',
      category: 'TV',
      brand: 'Samsung',
      price: 179.0,
      imageUrl: 'https://i.imgur.com/QNTUYwn.jpeg',
      specs: { size: '75"' },
    },
    {
      id: 168,
      name: 'Bravia XR 55" X90L Series 4K UHD HDR LED',
      category: 'TV',
      brand: 'Sony',
      price: 1999.0,
      imageUrl: 'https://i.imgur.com/D8u2rU3.png',
      specs: { size: '55"' },
    },
    {
      id: 169,
      name: 'Samsung 55" U7900F Series 4K UHD HDR LED Tizen Smart TV',
      category: 'TV',
      brand: 'Samsung',
      price: 1989.99,
      imageUrl: 'https://i.imgur.com/r5pWCsu.png',
      specs: { size: '55"' },
    },
    {
      id: 181,
      name: 'FURY Renegade 32GB',
      category: 'RAM',
      brand: 'Kingston',
      price: 189.99,
      imageUrl: 'https://i.imgur.com/Whepj0p.jpeg',
      specs: { capacity: '32GB', ddrVersion: 'DDR5' },
    },
    {
      id: 182,
      name: 'FURY Beast 32GB',
      category: 'RAM',
      brand: 'Kingston',
      price: 219.99,
      imageUrl: 'https://i.imgur.com/aHvJ4y1.png',
      specs: { capacity: '32GB', ddrVersion: 'DDR5' },
    },
    {
      id: 183,
      name: 'Kingston Fury Beast 16GB',
      category: 'RAM',
      brand: 'Kingston',
      price: 89.99,
      salePrice: 79.99,
      imageUrl: 'https://i.imgur.com/aHvJ4y1.png',
      specs: { capacity: '16GB', ddrVersion: 'DDR5' },
    },
    {
      id: 184,
      name: 'Ripjaws V 32GB',
      category: 'RAM',
      brand: 'G.Skill',
      price: 159.99,
      imageUrl: 'https://i.imgur.com/1I2LJFn.jpeg',
      specs: { capacity: '32GB', ddrVersion: 'DDR5' },
    },
    {
      id: 185,
      name: 'VENGEANCE RGB 64GB',
      category: 'RAM',
      brand: 'Corsair',
      price: 450.0,
      imageUrl: 'https://i.imgur.com/FhHltqE.jpeg',
      specs: { capacity: '64GB', ddrVersion: 'DDR5' },
    },
    {
      id: 186,
      name: 'Ripjaws X 32GB',
      category: 'RAM',
      brand: 'G.Skill',
      price: 170.0,
      salePrice: 149.0,
      imageUrl: 'https://i.imgur.com/nPPzUKO.png',
      specs: { capacity: '32GB', ddrVersion: 'DDR4' },
    },
    {
      id: 187,
      name: 'VENGEANCE 8GB',
      category: 'RAM',
      brand: 'Corsair',
      price: 45.0,
      imageUrl: 'https://i.imgur.com/4S0mK2m.png',
      specs: { capacity: '8GB', ddrVersion: 'DDR4' },
    },
    {
      id: 188,
      name: 'Trident Z RGB',
      category: 'RAM',
      brand: 'G.Skill',
      price: 75.0,
      salePrice: 59.0,
      imageUrl: 'https://i.imgur.com/r0Jhgon.png',
      specs: { capacity: '16GB', ddrVersion: 'DDR5' },
    },
    {
      id: 189,
      name: 'Corsair Vengeance LPX',
      category: 'RAM',
      brand: 'Corsair',
      price: 69.99,
      imageUrl: 'https://placehold.co/400x400/161B22/e6edf3?text=Vengeance+LPX',
      specs: { capacity: '16GB', ddrVersion: 'DDR5' },
    },
    {
      id: 190,
      name: 'Ripjaws V 16GB',
      category: 'RAM',
      brand: 'G.Skill',
      price: 65.0,
      imageUrl: 'https://i.imgur.com/mw2idlU.png',
      specs: { capacity: '16GB', ddrVersion: 'DDR4' },
    },
    {
      id: 191,
      name: 'Trident Z5 Neo RGB',
      category: 'RAM',
      brand: 'G.Skill',
      price: 399.0,
      salePrice: 349.0,
      imageUrl: 'https://i.imgur.com/7uCAekH.png',
      specs: { capacity: '64GB', ddrVersion: 'DDR5' },
    },
    {
      id: 193,
      name: 'Corsair Vengeance 64GB',
      category: 'RAM',
      brand: 'Corsair',
      price: 350.0,
      imageUrl: 'https://i.imgur.com/Af4GEbY.jpeg',
      specs: { capacity: '64GB', ddrVersion: 'DDR5' },
    },
    {
      id: 194,
      name: 'CORSAIR VENGEANCE RGB 32GB',
      category: 'RAM',
      brand: 'Corsair',
      price: 250.0,
      imageUrl: 'https://i.imgur.com/lPfD2zm.jpeg',
      specs: { capacity: '32GB', ddrVersion: 'DDR5' },
    },
    {
      id: 196,
      name: 'CORSAIR VENGEANCE LPX 32GB',
      category: 'RAM',
      brand: 'Corsair',
      price: 150.0,
      imageUrl: 'https://i.imgur.com/nwBi9vw.png',
      specs: { capacity: '32GB', ddrVersion: 'DDR4' },
    },
    {
      id: 197,
      name: 'Corsair Vengeance RGB 32GB',
      category: 'RAM',
      brand: 'Corsair',
      price: 199.99,
      imageUrl: 'https://i.imgur.com/mvoL79m.jpeg',
      specs: { capacity: '32GB', ddrVersion: 'DDR5' },
    },
  ])

  const cart = ref([])
  const uiStore = useUIStore()

  const cartItemCount = computed(() => {
    return cart.value.reduce((acc, item) => acc + item.quantity, 0)
  })

  const cartTotal = computed(() => {
    return cart.value.reduce((acc, item) => {
      const price = item.salePrice || item.price
      return acc + price * item.quantity
    }, 0)
  })

  const cartSavings = computed(() => {
    return cart.value.reduce((acc, item) => {
      if (item.salePrice) {
        return acc + (item.price - item.salePrice) * item.quantity
      }
      return acc
    }, 0)
  })

  function addToCart(productId) {
    const product = products.value.find((p) => p.id === productId)
    if (!product) return

    const cartItem = cart.value.find((item) => item.id === productId)
    if (cartItem) {
      cartItem.quantity++
    } else {
      cart.value.push({ ...product, quantity: 1 })
    }
    uiStore.showNotification(`${product.name} added to cart!`)
  }

  function removeFromCart(productId) {
    const index = cart.value.findIndex((item) => item.id === productId)
    if (index !== -1) {
      cart.value.splice(index, 1)
    }
  }

  function updateQuantity(productId, quantity) {
    const cartItem = cart.value.find((item) => item.id === productId)
    if (cartItem) {
      if (quantity > 0) {
        cartItem.quantity = quantity
      } else {
        removeFromCart(productId)
      }
    }
  }

  function clearCart() {
    cart.value = []
  }

  return {
    products,
    cart,
    addToCart,
    removeFromCart,
    updateQuantity,
    clearCart,
    cartItemCount,
    cartTotal,
    cartSavings,
  }
})
